services:
  web:
    tty: true
    build:
      context: .
    container_name: PB_Import_mysql
    ports:
      - "5000:5000"
    volumes:
      - ./:/home/uimm/Documents/PB.Importation
    depends_on:
      - db
      
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: PB_Import_mysql
      MYSQL_ROOT_PASSWORD: zebi
      MYSQL_USER: Léo
      MYSQL_PASSWORD: Léo
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./:/app/data
      - ./app/letsencrypt:/etc/letsencrypt
volumes:
  mysql-volume:
